version: "3.7"
services:
  postgres_cadastro:
    container_name: rango_cadastro
    image: postgres:12.2
    environment:
      POSTGRES_USER: rango_cadastro
      POSTGRES_PASSWORD: rango_cadastro
    ports:
      - "5431:5432"
  keycloak_rango:
    container_name: keycloak_rango
    image: jboss/keycloak:9.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  jaeger_rango:
    container_name: jaeger_rango
    image: jaegertracing/all-in-one:1.17
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  prometheus_rango:
    container_name: prometheus_rango
    image: prometheus-rango
    network_mode: "host"
  grafana_rango:
    container_name: grafana_rango
    image: grafana/grafana:7.3.7
    network_mode: "host"
